# Generated by Django 3.0.3 on 2020-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamish2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minerals',
            name='appearance',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='minerals',
            name='description',
            field=models.TextField(default='Enter Fun Facts Here!'),
        ),
        migrations.AlterField(
            model_name='minerals',
            name='symbol',
            field=models.CharField(max_length=3),
        ),
    ]
