# Generated by Django 3.0.3 on 2020-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamish2_app', '0002_auto_20200527_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='asx_code',
            field=models.CharField(default='ASX', max_length=8),
        ),
        migrations.AlterField(
            model_name='minerals',
            name='atomic_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
