# Generated by Django 3.0.3 on 2020-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamish2_app', '0003_auto_20200527_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minerals',
            name='mineral_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
